/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from 'grpc';

export namespace payments {
    // Тип документа
    export enum ExecutionType {
        // Не задано
        UNDEFINED = 0,
        // электронно
        ELECTRONIC = 1,
        // срочно
        URGENT = 2,
    }
    // типы документов
    export enum DocumentType {
        PAYMENT_REQUEST = 0,
    }
    export interface PaymentOrder {
        id?: number;
    }
}
export namespace google {
    export namespace protobuf {
        export interface DoubleValue {
            value?: number;
        }
        export interface FloatValue {
            value?: number;
        }
        export interface Int64Value {
            value?: number;
        }
        export interface UInt64Value {
            value?: number;
        }
        export interface Int32Value {
            value?: number;
        }
        export interface UInt32Value {
            value?: number;
        }
        export interface BoolValue {
            value?: boolean;
        }
        export interface StringValue {
            value?: string;
        }
        export interface BytesValue {
            value?: Uint8Array;
        }
        export interface Timestamp {
            seconds?: number;
            nanos?: number;
        }
    }
}

